[project]
name = "20251025-how-to-use-aws-bedrock-keys"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.57",
    "langchain>=1.0.2",
    "langchain-aws>=1.0.0",
]
